### PR TITLE
webedit roundtrip failed

### PR DESCRIPTION
**Pull request by AvdN**
If you have some project json files, startwebedit, go to an item and do nothing but save, the difference to the .json file edited was more than just a few fields added:

- URLs were removed.  this was a result from not having a `URLField` request type handler in `webedit:route_save()`, and was missed because unknown request types were silently ignored.
- TextFields with newlines had the newlines (`\n`) replaced by carriage return + newline (`\r\n`), leading to unnecessary differences.

This patch fixes both issues

### CODE REVIEW

**Comment by willkg** [comment]
This pr has commits from other prs in it. So we should resolve them first.

**Comment by AvdN** [comment]
Not sure why that is. Probably my long time aversion of git showing further influencing my incompetence. I already spent more time on trying to get this to commit than getting the bugs out ...

**Comment by willkg** [comment]
If it helps, I can cherry-pick your changes instead of using the big green merge button and also tweak git commit messages.

You're doing a lot of really helpful work. I'm happy to do whatever you need to reduce the pain in contributing.

**Comment by AvdN** [comment]
I'll give it another try tonight. If that doesn't work, I'll ask you to cherry pick that what you can use.

**Pull request closed without merging**
