### PR TITLE
Overhaul steve to use click

### PR DESCRIPTION
**Pull request by willkg**
Rewrites steve to use click for subcommand structure, help text,
argument parsing and output.

I also redid the entry points so that if steve throws an exception, it
yields a helpful text for writing up an issue.

Two big reasons to switch to click are:

1. the structure for subcommands, options and arguments is a lot easier
   to put together, read and understand than what we had before
2. it's way easier to test command line handlers and we should be doing
   that more

Subcommands and testing status:

* [x] createproject: automated test, passes
* [x] fetch: 
* [ ] pull: 
* [ ] push: 
* [x] scrapevideo: 
* [x] status: manual test, passes
* [x] verify: manual test, passes
* [x] webedit: manual test, passes

### CODE REVIEW

**Comment by willkg** [comment]
We have no tests for any of the command line code. I did some basic testing by hand, but I have no way to guarantee that this overhaul works right.

We could do one of two things here:

1. wait for me to write tests for all the commands which will take a long time--let's say a month
2. land it and fix things as they come up and write tests over time

I'm inclined to go with number 2. The person who will feel the most pain from this is @codersquid, though, so I'm going to let her decide what she's comfortable with.

@codersquid Thoughts?

**Comment by codersquid** [comment]
I'm fine with the landit plan! land it and fix things as they come up. It's really easy to smoke test this.

**Comment by AvdN** [comment]
this breaks `steve-cmd createproj testproj` with:

    Steve: '0.5.dev'
    Python: '2.7.10 (default, Aug 24 2015, 17:46:52) \n[GCC 4.8.4]'
    Command line: ['/home/venv/steve/bin/steve-cmd', 'createproject', 'testproj']
    Traceback (most recent call last):
      File "/home/venv/steve/bin/steve-cmd", line 9, in <module>
        load_entry_point('steve==0.5.dev0', 'console_scripts', 'steve-cmd')()
      File "/data1/src/steve.org/steve/cmdline.py", line 76, in click_run
        cli(obj={})
      File "/home/venv/steve/lib/python2.7/site-packages/click/core.py", line 700, in __call__
        return self.main(*args, **kwargs)
      File "/home/venv/steve/lib/python2.7/site-packages/click/core.py", line 680, in main
        rv = self.invoke(ctx)
      File "/home/venv/steve/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/venv/steve/lib/python2.7/site-packages/click/core.py", line 873, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/venv/steve/lib/python2.7/site-packages/click/core.py", line 508, in invoke
        return callback(*args, **kwargs)
      File "/home/venv/steve/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/data1/src/steve.org/steve/cmdline.py", line 97, in createproject
        path = os.path.abspath(directory)
      File "/home/venv/steve/lib/python2.7/posixpath.py", line 360, in abspath
        if not isabs(path):
      File "/home/venv/steve/lib/python2.7/posixpath.py", line 54, in isabs
        return s.startswith('/')
    AttributeError: 'tuple' object has no attribute 'startswith'

I suggest you merge my PR34, and run tox before merging this.

**Comment by willkg** [comment]
I merged the tox PR in, cleaned up the flake8 issues and fixed the docs and requirements. That's all in the master branch.

Then I rebased this commit on top of that, fixed the new flake8 issues, rewrote the test that runs createproject, fixed the issue causing it to fail and did some other minor cleanup.

Thank you @AvdN! That was super helpful!

I think I'm going to spend some time writing tests for or manually testing all the commands. I'll write up a list in the PR description and maintain the status there.

**Comment by willkg** [comment]
^^^ That adds a bunch more command line tests. Plus it fixes a bunch of issues with commands. The only two I didn't test are pull/push.

Pull/push are probably things only @codersquid is going to use. So I'm going to land this now and then fix those if issues come up with her usage.

**Comment by codersquid** [comment]
:bouquet: :+1: :beers: :cake: thanks!

**Pull request merged**
